# Add the bot's token here, you can get that from
# the Discord Developer Portal https://discord.com/developers/
token: ''
prefix: .
# the whitelist is managed by the bot do not touch
whitelist:
  - ''
# Here's an example of a custom emoji ":name:emoji id"
# ie. :pewDownvote:718677670342426646
emojis:
  - ğŸ‘
  - ğŸ‘